### ISSUE TITLE
Create Xcode project

### ISSUE THREAD

**Issue by kirpichonok** [ios-course/link-team-project#1]
AC: 
- The name of the project "JourneysSquad".

- Minimum Deployments: 16
- Supported Destinations: iPhone
- iPhone modes: portrait 
- Dark/night theme - deactivate

**Additional settings:**

- add swiftlint, version 0.51.0 (add config file in the root direction of repo and add to [script](https://github.com/nicklockwood/SwiftFormat#xcode-build-phase) to build phase)
- add swiftformat,  version 0.51.7 (add config file in the root direction of repo)
- swift-version 5.8

**swiftFormat rules:**
```
# format options
--funcattributes same-line
--ranges no-space

#rules
--disable \
         redundantPattern, \
         wrapMultilineStatementBraces,

--enable \
        wrapEnumCases

# minimum swift format version
--minversion 0.51.7
```
**swiftLint rules:**
```
trailing_comma:
    mandatory_comma: true
    
identifier_name:
    excluded: ["id", "a", "b", "c", "i", "j", "x", "y", "z"]
```

- versioning will be carried out according to SemVer;
- will use [GitHub-Flow](https://docs.github.com/en/get-started/quickstart/github-flow#);
- will use tags to up the version;
